server:
  port: 8101

spring:
  application:
    name: admin-order
  boot:
    admin:
      client:
        url: http://127.0.0.1:8001
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: false
  endpoints: #监控对外开放
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

