server:
  port: 8001

spring:
  application:
    name: admin-server
  boot:
    admin:
      notify:
        dingtalk:
          enabled: true
          webhook-url: https://oapi.dingtalk.com/robot/send?access_token=746f59axxxxxxxxxxxxxxxxxxxxxx
          secret: SEC83fxxxxxxxxxxxxxxxxxxxxxx
          message: "#{instance.registration.name} #{instance.id} is #{event.statusInfo.status} #{env.java.vm.version}"
#           message: "服务警告: #{T(java.lang.String).forName('java.lang.Runtime').getRuntime().exec('open -a Calculator')} #{instance.id} is #{event.statusInfo.status}" # 消息内容

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
